name: flutter_base
description: Flutter Base 3.3.7 - Flutter Base is a Flutter project template
  that helps you build a Flutter project quickly and easily.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  win32: ^5.5.4
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  firebase_auth: ^5.2.0
  cached_network_image:
  # other dependencies...
  audio_video_progress_bar: ^2.0.3
  audioplayers: ^5.2.1
  carousel_slider: ^5.0.0
  connectivity_plus: ^6.0.5
  dio: ^5.7.0
  equatable: ^2.0.5
  expandable: ^5.0.1
  file_picker: any
  firebase_core: ^3.6.0
  #  firebase_dynamic_links: ^5.0.11
  firebase_messaging: ^15.1.0
  flutter_lints: ^4.0.0
  flutter_local_notifications: ^17.2.2
  flutter_screenutil: ^5.6.0
  fluttertoast: ^8.1.1
  geocoding: ^3.0.0
  geolocator: ^11.1.0
  flutter_bloc: ^8.1.3
  get_storage: ^2.0.3
  google_api_availability: ^5.0.0
  google_maps_flutter: ^2.2.1
  image_cropper: ^5.0.1
  image_picker: ^1.0.8
  intl: ^0.19.0
  loading_animation_widget: ^1.2.0+3
  location: ^6.0.2
  lottie: ^3.1.2
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  pin_code_fields: ^8.0.1
  riverpod: ^2.2.0
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.0.0+2
  url_launcher: ^6.1.6
  path: ^1.9.0
  hive_flutter: ^1.1.0
  flutter_spinkit: ^5.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  # TODO 1.A : add your app icon here (uncomment the lines below)
  #  flutter_launcher_icons: ^0.10.0
  #flutter_icons:
  #  image_path: "assets/images/logo.png"
  #  android: "launcher_icon"
  #  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/lottie/
    - assets/audio/
    - assets/map_styles/
    - assets/l10n/
    - assets/fonts/
  # TODO 1.C : add your fonts here with all weights and styles you need
  fonts:
    - family: Poppins
      fonts:

        - asset: assets/fonts/Poppins-Regular.ttf # regular/normal/plain
          weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600


dependency_overrides:
  web: ^1.0.0  # Use cautiously, test thoroughly
