part of 'imports_decoration.dart';
class InputDecorationWithOutBorder extends InputDecorationImp {
  InputDecorationWithOutBorder({
    Color? borderColor,
    Color? enableBorderColor,
    Color? disableBorderColor,
    Color? focusBorderColor,
    Color? errorBorderColor,
    double? borderRadius,
    double? enableBorderRadius,
    double? disableBorderRadius,
    double? focusBorderRadius,
    double? errorBorderRadius,
    double? borderWidth,
    double? enableBorderWidth,
    double? disableBorderWidth,
    double? focusBorderWidth,
    double? errorBorderWidth,
    Color? filledColor,
  }) : super(
          borderColor: borderColor,
          enableBorderColor: enableBorderColor,
          disableBorderColor: disableBorderColor,
          focusBorderColor: focusBorderColor,
          errorBorderColor: errorBorderColor,
          borderRadius: borderRadius,
          enableBorderRadius: enableBorderRadius,
          disableBorderRadius: disableBorderRadius,
          focusBorderRadius: focusBorderRadius,
          errorBorderRadius: errorBorderRadius,
          borderWidth: borderWidth,
          enableBorderWidth: enableBorderWidth,
          disableBorderWidth: disableBorderWidth,
          focusBorderWidth: focusBorderWidth,
          errorBorderWidth: errorBorderWidth,
          filledColor: filledColor,
        );
}
