const Map<String, String> arEG = {
  "about_app": "عن التطبيق",
  "from_camera": "من الكاميرا",
  "from_gallery": "من المعرض",
  "confirm": "تأكيد",
  "cancel": "إلغاء",
  "enter": "دخول",
  "back": "رجوع",
  "next": "التالي",
  "done": "تم",
  "save": "حفظ",
  "start": "بدء",
  "skip": "تخطي",
  "delete": "حذف",
  "edit": "تعديل",
  "add": "إضافة",
  "clear": "مسح",
  "search_anything": "بحث عن أي شيء",
  "search": "بحث",
  "no_data_to_copy": "لا يوجد بيانات للنسخ",
  "show_all": "عرض الكل",
  "?": "؟",
  "onBoarding_title_1": "",
  "onBoarding_body_1": "",
  "onBoarding_title_2": "",
  "onBoarding_body_2": "",
  "onBoarding_title_3": "",
  "onBoarding_body_3": "",
  "illustration_no_connection": "تم قطع الإتصال",
  "illustration_no_connection_details":
      "عذرا تم قطع الاتصال بالإنترنت , تأكد من الاتصال و أعد المحاولة في وقت لاحق",
  "illustration_something_went_wrong": "حدث خطأ ما",
  "illustration_something_went_wrong_details":
      "حدث خطأ ما , تأكد من اتصالك و أعد المحاولة في وقت لاحق",
  "illustration_no_notifications": "لا يوجد إشعارات",
  "illustration_no_notifications_details": "لا يوجد إشعارات حتى الآن",
  "illustration_unknown": "خطأ غير معروف",
  "illustration_unknown_details":
      "حدث خطأ غير معروف , يرجى المحاولة مرة أخرى في وقت لاحق",
  "validate_address": "عفوا لم يتم ادخال عنوان",
  "validate_admin_adjective": "عفوا لم يتم صفه المسؤول",
  "validate_age": "من فضلك أدخل عمر صحيح",
  "validate_age_limit": "يجب أن لا يقل العمر عن 16 سنة",
  "validate_city": "عفوا لم يتم اختيار مدينه",
  "validate_confirm_password": "عفوا كلمة المرور غير متطابقة",
  "validate_date_of_birth": "عفوا لم يتم ادخال تاريخ ميلاد",
  "validate_email": "عفوا لم يتم ادخال بريد مستخدم صحيح",
  "validate_email_2": "من فضلك أدخل بريد إلكتروني صحيح",
  "validate_empty_field":
      "الحقل فارغ. من فضلك تأكد من ملء بيانات الحقل المطلوبة",
  "validate_lang": "عفوا لم يتم اختيار اللغات",
  "validate_language": " يجب على الأقل أن تختار لغة واحدة للمتابعة",
  "validate_message": "عفوا لم يتم ادخال رسالة صحيحة",
  "validate_numeric": "يجب أن تكون البيانات المدخلة أرقام",
  "validate_offered_service": "عفوا لم يتم اختيار الخدمة المقدمة",
  "validate_password": "عفوا لم يتم ادخال كلمة مرور صحيحة",
  "validate_password_length": "يجب ألا تقل كلمة المرور عن 6 أحرف أو أرقام",
  "validate_phone": "عفوا لم يتم ادخال رقم هاتف صحيح",
  "validate_phone_is_real": "! حاول مرة أخرى برقم هاتف صحيح",
  "validate_promo": "عفوا لم يتم ادخال كود صحيح",
  "validate_skills": "عفوا لم يتم اختيار المهارات",
  "validate_username": "عفوا لم يتم ادخال اسم مستخدم صحيح",
  "validate_username_length": "يجب أن يكون اسم المستخدم مكون من أكثر من حرفين",
  "snack_check_ur_connection": "تأكد من اتصالك بالإنترنت",
  "snack_something_went_wrong": "حدث خطأ ما",
  "snack_success": "تم بنجاح",
  "snack_error": "حدث خطأ ما",
  "snack_login_success": "تم تسجيل الدخول بنجاح",
  "snack_logout_success": "تم تسجيل الخروج بنجاح",
  "snack_register_success": "تم التسجيل بنجاح",
  "snack_short_password": "كلمة المرور قصيرة جدا",
  "snack_validate_number": "يجب أن تكون البيانات المدخلة أرقام",
  "success_password": "تم تغيير كلمة المرور بنجاح",
  "success_phone_verify": "تم تفعيل الهاتف بنجاح",
  "success_message_sent": "تم إرسال الرسالة بنجاح",
  "success_username": "تم تغيير اسم المستخدم بنجاح",
  "success_birthday": "تم تغيير تاريخ الميلاد بنجاح",
  "success_image": "تم تغيير الصورة بنجاح",

  /// TODO: add new keys
  "ex_bad_request": "خطأ في الطلب",
  "ex_unauthorized": "غير مصرح لك بالوصول",
  "ex_forbidden": "ممنوع",
  "ex_not_found": "غير موجود",
  "ex_method_not_allowed": "الطريقة غير مسموح بها",
  "ex_not_acceptable": "غير مقبول",
  "ex_request_timeout": "انتهت مهلة الطلب",
  "ex_conflict": "حدث تعارض",
  "ex_internal_Server": "خطأ في الخادم",
  "ex_not_implemented": "لم يتم تنفيذه",
  "ex_bad_gateway": "بوابة سيئة",
  "ex_service_unavailable": "الخدمة غير متوفرة",
  "ex_gateway_timeout": "انتهت مهلة البوابة",
  "ex_unknown": "خطأ غير معروف",
  "ex_network": "خطأ في الشبكة",
};
