


const Map<String, String> enUS = {
  "about_app": "About the application",
  "from_camera": "From Camera",
  "from_gallery": "From Gallery",
  "confirm": "Confirm",
  "cancel": "Cancel",
  "enter": "Enter",
  "back": "Back",
  "next": "Next",
  "done": "Done",
  "save": "Save",
  "start": "Start",
  "skip":"Skip",
  "delete": "Delete",
  "edit": "Edit",
  "add": "Add",
  "clear": "Clear",
  "search_anything": "Search anything",
  "search": "Search",
  "no_data_to_copy": "No data to copy",
  "show_all": "Show All",
  "?": "؟",
  "onBoarding_title_1": "-",
  "onBoarding_body_1": "-",
  "onBoarding_title_2": "-",
  "onBoarding_body_2": "-",
  "onBoarding_title_3": "-",
  "onBoarding_body_3": "-",
  "illustration_no_connection": "The connection has been cut off",
  "illustration_no_connection_details":
      "Sorry,internet connection has been cut,be sure to connect and try at a later time",
  "illustration_something_went_wrong": "An error occurred",
  "illustration_something_went_wrong_details":
      "An error occurred,make sure you contact and try at a later time",
  "illustration_no_notifications": "No notifications",
  "illustration_no_notifications_details": "No notifications yet",
  "illustration_unknown": "Unknown error",
  "illustration_unknown_details":
      "There was an unknown error,please try again later",
  "validate_address": "Sorry,no address has been entered",
  "validate_admin_adjective": "Sorry,the official was not described",
  "validate_age": "Please enter a right life",
  "validate_age_limit": "It should not be less than 16 years old",
  "validate_city": "Sorry,a city was not chosen",
  "validate_confirm_password": "Sorry,the password is not identical",
  "validate_date_of_birth": "Sorry,the date of birth was not entered",
  "validate_email": "Sorry,a correct user mail was not inserted",
  "validate_email_2": "Please enter a correct email",
  "validate_empty_field":
      "The field is empty. Please make sure to fill the required field data",
  "validate_lang": "Sorry,the languages were not chosen",
  "validate_language": "At least you must choose one language to follow",
  "validate_message": "Sorry,the correct message was not entered",
  "validate_numeric": "The data entered must be numbers",
  "validate_offered_service": "Sorry,the service provided has not been chosen",
  "validate_password": "Sorry,the correct password has not been entered",
  "validate_password_length":
      "The password should not be less than 6 letters or numbers",
  "validate_phone": "Sorry,the correct phone number has not been entered",
  "validate_phone_is_real": "! Try again with a correct phone number",
  "validate_promo": "Sorry,the correct code has not been entered",
  "validate_skills": "Sorry,the skills have not been chosen",
  "validate_username": "Sorry,the name of a correct user has not been entered",
  "validate_username_length":
      "The username must be made up of more than two letters",
  "snack_check_ur_connection": "Check your internet connection",
  "snack_something_went_wrong": "Something went wrong",
  "snack_success": "Done successfully",
  "snack_error": "apparently, an error occurred",
  "snack_login_success": "Login successfully",
  "snack_logout_success": "Logout successfully",
  "snack_register_success": "Registration successfully",
  "snack_short_password":
      "The password should not be less than 6 letters or numbers",
  "snack_validate_number": "Please enter a correct number",
  "success_password": "Password changed successfully",
  "success_phone_verify": "Phone number verified successfully",
  "success_message_sent": "Message sent successfully",
  "success_username": "UserName updated successfully",
  "success_birthday": "Birthday updated successfully",
  "success_image": "Image updated successfully",
};
