import 'package:flutter_base/src/Core/Constants/strings/assets.dart';
import 'package:flutter_base/src/Core/Utils/Extensions/screen_spaces_extension.dart';
  import 'package:flutter_base/src/Shared/Presentation/Widgets/Builders/conditional_builder.dart';
import 'package:flutter_base/src/Shared/Presentation/Widgets/GeneralWidgets/Buttons/Customizable/imports_customizable.dart';
import 'package:flutter_base/src/Shared/Presentation/Widgets/GeneralWidgets/Image/generic_image/generic_image.dart';
import 'package:flutter_base/src/Shared/Presentation/Widgets/GeneralWidgets/Text/custom_text_lib.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
part 'Illustration_page_builder.dart';